# Generated by Django 4.0.1 on 2022-04-27 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('date_paid', models.DateField(default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
                ('poster', models.ImageField(upload_to='images')),
                ('category', models.CharField(choices=[('TRENDING NOW', 'Trending Now'), ('TV SHOWS', 'TV Shows'), ('TOP PICKS', 'Top Picks'), ('MUST WATCH', 'Must Watch Shows'), ('AGAIN', 'Watch It Again')], default='MUST WATCH', max_length=25)),
                ('trailer', models.URLField()),
                ('users', models.ManyToManyField(blank=True, default=None, null=True, to='Netflix.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_cnt', models.IntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Netflix.movies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Netflix.customer')),
            ],
        ),
    ]
