# Generated by Django 4.0.1 on 2022-04-27 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Netflix', '0003_alter_movies_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
