# Generated by Django 4.0.1 on 2022-05-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Netflix', '0005_movies_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='users',
        ),
        migrations.AddField(
            model_name='movies',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
