# Generated by Django 4.0.1 on 2022-05-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Netflix', '0008_alter_movies_price_alter_movies_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='price',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='movies',
            name='stripe_id',
            field=models.CharField(default='prod_LcUWfaSFEc2WbH', max_length=50),
        ),
    ]
