# Generated by Django 4.0.1 on 2022-05-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Netflix', '0009_alter_movies_price_alter_movies_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='stripe_id',
            field=models.CharField(max_length=50),
        ),
    ]
